export const SkinCare = {
  SkinType: ["Oily", "Dry", "Combination", "Sensitive", "Normal"],
  currentProducts: [
    "Mist",
    "Spot Treatment",
    "Makeup Remover",
    "Exfoliator",
    "Toner",
    "Moisturizers",
    "Sunscreen",
    "Serum",
    "Essence",
  ],
  allergies: ["Yes (Please Specify)", "No"],
  primaryConcern: [
    "Acne",
    "Dark spots",
    "Eczema",
    "Stretch marks",
    "Dry Skin",
    "Oily skin",
    "Shaving bumps",
    "Hyperpigmentation",
  ],
  routine: ["Simple (1-3 steps)", "Moderate(4-6 steps)", "Extensive (7+ steps"],
};

export const HairCare = {
  concerns: [
    "Frizz",
    "Dryness",
    "Thinning",
    "Dandruff",
    "Oily Scalp",
    "Split Ends",
    "Breakage",
    "Color-treated",
    "Volume",
    "Hair Loss",
  ],
  regularProducts: [
    "Shampoo",
    "Conditioneer",
    "Hair Mask",
    "Leave-in Conditioner",
    "Hair Oil",
    "Mousse",
    "heat Protectant",
    "Hair Spray",
    "Serum",
  ],
  washFrequency: [
    "Daily",
    "Every Other Day",
    "Twice a Week",
    "Weekly",
    "Less than weekly",
  ],
  hairType: ["Straight", "Wavy", "Curly", "Coily"],
  heatStylingTools: ["Hair Dryer", "Straightener", "Curling Iron", "None"],
  allergies: ["Yes (Please Specify)", "No"],
};

export const Cosmetics = {
  dailyProducts: [
    "Foundation",
    "Concealer",
    "Powder",
    "Blush",
    "Highlighter",
    "Bronzer",
    "Eyeshadow",
    "Eyeliner",
    "Lip Gloss",
    "Mascara",
    "Eyebrow pencil",
    "Lipstick",
    "Lip Balm",
    "Setting Spray",
  ],
  allergies: ["Yes (Please Specify)", "No"],
  preferredFinishes: ["Matte", "Dewy", "Natural", "Satin", "Luminous"],
  concerns: [
    "Long-lasting",
    "Non-comedogenic",
    "Waterproof",
    "Full Coverage",
    "Lightweight",
    "Hydrating",
    "Mattifying",
  ],
};

export const Fragrances = {
  allergies: ["Yes (Please Specify)", "No"],
  perfumeUseFrequency: [
    "Daily",
    "Occasionally",
    "Special Events Only",
    "Rarely",
    "Never",
  ],
  strengthPreference: ["Strong", "Subtle", "Moderate", "Sensitive"],

  preferredScents: [
    "Fruity",
    "Citrus",
    "Woody",
    "Floral",
    "Spicy",
    "Fresh",
    "Oriental",
    "Aquatic",
    "Musk",
    "Gourmand",
  ],
};

export const PersonalInfo = {
  age: [18, 25, 35, 45, 55, 65],
  gender: ["Female", "Male", "Non Binary", "Prefer not to say"],
};

export const ProductPreferences = {
  dietaryRestrictions: [
    "Vegan",
    "Cruelty-free",
    "Gluten-free",
    "Organic",
    "Non-GMO",
    "Natural Ingredients",
    "None",
  ],
  ingredientsToAvoid: [
    "Parabens",
    "Sulfates",
    "Artificial Fragrances",
    "Phtalates",
    "Alcohol",
    "Silicones",
    "Mineral Oil",
    "Gluten",
    "Talc",
    "Formaldehyde",
  ],
  preferredCategory: "",
  preferredNaturalIngredients: [
    "Aloe Vera",
    "Tea Tree Oil",
    "Argan Oil",
    "Shea Butter",
    "Coconut Oil",
    "Jojoba Oil",
    "Hyaluronic Acid",
    "Green Tea",
    "Chamomile",
    "Rosehip Oil",
    "Vitamin C",
    "Retinol",
  ],
};

export const validUnits = [
  // Weight units
  // "kilogram",
  //"kilograms",
  "kg",
  // "gram",
  // "grams",
  "g",
  //"milligram",
  //"milligrams",
  "mg",
  //"pound",
  //"pounds",
  "lb",
  //"ounce",
  //"ounces",
  "oz",
  //"tonne",
  //"tonnes",
  "t",
  //"carat",
  //"carats",
  "ct",
  //"grain",
  //"grains",
  "gr",
  //"metric ton",
  //"metric tonnes",
  "mt",
  //"short ton",
  //"short tons",
  "sh. t.",
  //"long ton",
  //"long tons",
  "l. t.",
  //"hundredweight",
  //"hundredweights",
  "cwt",
  //"stone",
  //"stones",
  "st",

  // Volume units
  //"liter",
  //"liters",
  "l",
  // "milliliter",
  // "milliliters",
  "ml",
  // "gallon",
  //"gallons",
  "gal",
  // "quart",
  //"quarts",
  "qt",
  //"pint",
  //"pints",
  "pt",
  //"fluid ounce",
  //"fluid ounces",
  "fl oz",
  //"cubic meter",
  // "cubic meters",
  "m3",
  // "cubic foot",
  // "cubic feet",
  "ft3",
  // "cubic inch",
  // "cubic inches",
  "in3",
  //cup
  //cups
  "c",
  //teaspoon
  //teaspoons
  "tsp",
  //tablespoon
  //tablespoons
  "tbsp",
];
